#!/bin/bash
# ──────────────────────────────────────────────────────────────
#  NeuronCLI Installer — Works on ANY Linux/macOS
#  Usage: curl -fsSL https://raw.githubusercontent.com/RAHUL-DevelopeRR/neuroncli/master/install.sh | bash
#
#  Creates: ~/.neuroncli/venv/  (isolated Python environment)
#           ~/.local/bin/neuron (global command)
#
#  No pipx, no sudo, no --break-system-packages. Just works.
# ──────────────────────────────────────────────────────────────

set -e

INSTALL_DIR="$HOME/.neuroncli"
VENV_DIR="$INSTALL_DIR/venv"
BIN_DIR="$HOME/.local/bin"
WRAPPER="$BIN_DIR/neuron"

echo ""
echo "  ╔════════════════════════════════════════╗"
echo "  ║     NeuronCLI Installer                ║"
echo "  ║     Free AI Coding Agent               ║"
echo "  ╚════════════════════════════════════════╝"
echo ""

# ── Step 1: Check Python ──────────────────────────────────────
PYTHON=""
for cmd in python3 python; do
    if command -v "$cmd" &>/dev/null; then
        version=$("$cmd" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')" 2>/dev/null)
        major=$(echo "$version" | cut -d. -f1)
        minor=$(echo "$version" | cut -d. -f2)
        if [ "$major" -ge 3 ] && [ "$minor" -ge 10 ]; then
            PYTHON="$cmd"
            break
        fi
    fi
done

if [ -z "$PYTHON" ]; then
    echo "  [X] Python 3.10+ required."
    echo "      Install: sudo apt install python3 python3-venv"
    exit 1
fi
echo "  [v] Python $version found ($PYTHON)"

# ── Step 2: Ensure python3-venv is available ──────────────────
if ! "$PYTHON" -m venv --help &>/dev/null; then
    echo "  [!] python3-venv not installed. Installing..."
    if command -v apt &>/dev/null; then
        sudo apt install -y python3-venv python3-pip 2>/dev/null || {
            echo "  [X] Could not install python3-venv."
            echo "      Run: sudo apt install python3-venv python3-pip"
            exit 1
        }
    elif command -v dnf &>/dev/null; then
        sudo dnf install -y python3-pip 2>/dev/null || true
    fi
fi

# ── Step 3: Create isolated venv ──────────────────────────────
echo "  [.] Creating isolated environment..."
mkdir -p "$INSTALL_DIR"

if [ -d "$VENV_DIR" ]; then
    echo "  [.] Upgrading existing installation..."
    "$VENV_DIR/bin/pip" install --upgrade neuroncli --quiet 2>/dev/null
else
    "$PYTHON" -m venv "$VENV_DIR"
    "$VENV_DIR/bin/pip" install --upgrade pip --quiet 2>/dev/null
    "$VENV_DIR/bin/pip" install neuroncli --quiet
fi
echo "  [v] NeuronCLI installed"

# ── Step 4: Create global 'neuron' command ────────────────────
mkdir -p "$BIN_DIR"

cat > "$WRAPPER" << 'WRAPPER_SCRIPT'
#!/bin/bash
# NeuronCLI launcher — auto-generated by install.sh
exec "$HOME/.neuroncli/venv/bin/neuron" "$@"
WRAPPER_SCRIPT

chmod +x "$WRAPPER"
echo "  [v] 'neuron' command created at $WRAPPER"

# ── Step 5: Ensure ~/.local/bin is in PATH ────────────────────
IN_PATH=false
case ":$PATH:" in
    *":$BIN_DIR:"*) IN_PATH=true ;;
esac

if [ "$IN_PATH" = false ]; then
    # Add to shell config
    SHELL_RC=""
    if [ -f "$HOME/.bashrc" ]; then
        SHELL_RC="$HOME/.bashrc"
    elif [ -f "$HOME/.zshrc" ]; then
        SHELL_RC="$HOME/.zshrc"
    elif [ -f "$HOME/.profile" ]; then
        SHELL_RC="$HOME/.profile"
    fi

    if [ -n "$SHELL_RC" ]; then
        if ! grep -q '\.local/bin' "$SHELL_RC" 2>/dev/null; then
            echo '' >> "$SHELL_RC"
            echo '# NeuronCLI' >> "$SHELL_RC"
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$SHELL_RC"
            echo "  [v] Added ~/.local/bin to PATH in $(basename "$SHELL_RC")"
        fi
    fi
    export PATH="$BIN_DIR:$PATH"
fi

# ── Step 6: Verify ───────────────────────────────────────────
echo ""
if command -v neuron &>/dev/null || [ -x "$WRAPPER" ]; then
    VERSION=$("$VENV_DIR/bin/neuron" --version 2>/dev/null || echo "installed")
    echo "  ════════════════════════════════════════"
    echo "  ✓ NeuronCLI $VERSION"
    echo "  ════════════════════════════════════════"
    echo ""
    echo "  Run 'neuron' in any project directory."
    echo "  If 'neuron' is not found, restart your terminal."
    echo ""
else
    echo "  [X] Installation failed. Try manually:"
    echo "      python3 -m venv ~/.neuroncli/venv"
    echo "      ~/.neuroncli/venv/bin/pip install neuroncli"
    echo "      ~/.neuroncli/venv/bin/neuron"
fi
